package es.babel.schedule;

import java.util.ResourceBundle;

import javax.annotation.PostConstruct;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import es.babel.db.DBUtil;
import es.babel.db.DataCRUD;
import es.babel.model.DataModel;

public class InitializationService {
	
	public static final Log log = LogFactory.getLog(InitializationService.class);

	@PostConstruct
	public void initIt() throws Exception {
		log.info("Checking for initial configuration");
		
		ResourceBundle configDB = ResourceBundle.getBundle("configuration");
		Boolean reset = Boolean.valueOf(configDB.getString("data.reset"));
		Boolean populate = Boolean.valueOf(configDB.getString("populate.testing.data"));
		
		if(!DBUtil.checkDataTable()){
			log.info("No data found. Creating basic data structure");
			DBUtil.createDataTable();
		}else{
			log.info("Previous data found");
			if(reset){
				log.info("Reset enabled. Clearing data");
				DBUtil.dropDataTable();
				DBUtil.createDataTable();
				if(populate){
					log.info("Populating with test data");
					for(int i=0; i<25; i++){
						DataModel data = new DataModel(i, 0, 20182, false, 0, "test"+i, "test"+i, "test"+i, "test"+i, "", "url", "", false, "/autogenerated"+i);
						DataCRUD.createData(data);
					}
				}
			}
		}
	}
}
